config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  namespace :public do
    get "home/about" => "homes#about"
    resources :charas, only:[:index, :edit, :show, :create, :destroy, :update] do
      resources :chara_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :free_comments, only:[:index, :create, :destroy]
    resources :customers, only:[:index, :edit, :show]
  end
  
  scope module: :public do
    root to: "homes#top"
  end
  
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    
  end
  
  devise_scope :customer do
    post 'customer/guest_sign_in', to: 'customers/sessions#guest_sign_in'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chara.rb
class Chara < ApplicationRecord
    belongs_to :customer
    has_many :chara_comments, dependent: :destroy
    has_many :free_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    validates :name, presence:true
    validates :delete_key, format:{with: /\A\w{1,100}\z/i } #リファクタリングで正規表現を使用しました！
    
    def favorited_by?(customer)
        favorites.where(customer_id: customer.id).exists?
    end
end

app/models/chara_comment.rb
class CharaComment < ApplicationRecord
    belongs_to :customer
    belongs_to :chara
    
    validates :comment, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :charas, dependent: :destroy
  has_many :chara_comments, dependent: :destroy
  has_many :free_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg' #論理演算子でリファクタリング
  end
  
  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestuser"
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :customer
    belongs_to :chara
    validates_uniqueness_of :chara_id, scope: :customer_id
end

app/models/free_comment.rb
class FreeComment < ApplicationRecord
    belongs_to :customer
    belongs_to :chara
    
    validates :comment, presence: true
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
        root_path
    end
    
    def after_sign_out_path_for(resource)
        root_path
    end
    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
    
end

app/controllers/customers/sessions_controller.rb
class Customers::SessionsController < Devise::SessionsController
   
   def guest_sign_in
       customer = Customer.guest
       sign_in customer
       redirect_to root_path, notice:'ゲストユーザーでログインしました'
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charas_helper.rb
module CharasHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/charas/edit.html.erb
<h1>Charas#edit</h1>
<p>Find me in app/views/charas/edit.html.erb</p>

app/views/charas/show.html.erb
<h1>Charas#show</h1>
<p>Find me in app/views/charas/show.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="position-relative">
<div class="navbar navbar-expand-lg navbar-light bg-info text-light position-absolute bottom-0 w-100 bg-dark pt-5 pb-4">
    <div class="container">
        <div class="row mx-auto">
                <h1 class="mx-auto">CopyRight ■■■■■■■■■</h1>
            <div class="col-md-6 mx-auto">
            <ul class="navbar-nav">
                <li>
                <%=link_to 'https://twitter.com/?lang=ja', class: 'nav-link text-light' do%>
                    <i class="fab fa-twitter display-2"></i>
                <%end%>
                </li>
                <li>
                <%=link_to 'https://www.instagram.com/', class: 'nav-link text-light' do%>
                    <i class="fab fa-instagram display-2"></i>
                <%end%>
                </li>
                <li>
                <%=link_to 'https://ja-jp.facebook.com/', class: 'nav-link text-light' do%>
                    <i class="fab fa-facebook display-2"></i>
                <%end%>
                </li>
            </ul>
            </div>
        </div>
    </div> 
</div>
</div>

app/views/layouts/_header.html.erb
      <nav class="navbar navbar-expand-lg navbar-light bg-info p-5">
        <div class="container">
          <a class="navbar-brand text-light" href="/"><i class="fa fa-birthday-cake"></i> <span>KuraChara</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-lavel="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <%if customer_signed_in?%>
              <li>
                <%= link_to public_customer_path(current_customer), method: :get, class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i> ホーム
                <%end%>
              </li>
              <li>
                <%= link_to public_customers_path, method: :get, class: 'nav-link text-light' do %>
                  <i class="fas fa-users"></i> 会員一覧
                <%end%>
              </li>
              <li>
                <%= link_to public_charas_path, method: :get, class: 'nav-link text-light' do %>
                  <i class="fas fa-book-open"></i> 投稿
                <%end%>
              </li>
              <li>
                <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-out-alt"></i> ログアウト
                <%end%>
              </li>
              <li>
                <%= link_to public_free_comments_path, method: :get, class: 'nav-link text-light' do %>
                  <i class="fas fa-comment"></i> フリーコメント
                <%end%>
              </li>
              <%else%>
              
              <li>
                <%= link_to root_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i> ホーム
                <%end%>
              </li>
              <li>
                <%= link_to public_home_about_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-store"></i> サイト紹介
                <%end%>
              </li>
              <li>
                <%= link_to new_customer_registration_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i> 会員登録
                <%end%>
              </li>
              <li>
                <%= link_to new_customer_session_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i> ログイン
                <%end%>
              </li>
              <li>
                <%= link_to customer_guest_sign_in_path, class: 'nav-link text-light', method: :post do %>
                  <i class="fa fa-user"></i> ゲストログイン
                <% end %>
              </li>
              <%end%>
            </ul>
          </div>
        </div>
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KuraChara</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header'%>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer'%>
    </footer>
  </body>
</html>